import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeContextProvider } from "@/context/theme-context/ThemeContext";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "Cristiane Aguiar Studio",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: "100",
  subsets: ["latin"],
  variable: "--font-poppins-thin",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={poppins.variable}>
      <body>
        <ThemeContextProvider>{children}</ThemeContextProvider>
      </body>
    </html>
  );
}
