import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeContextProvider } from "@/context/theme-context/ThemeContext";

export const metadata: Metadata = {
  title: "Cristiane Aguiar Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <ThemeContextProvider>{children}</ThemeContextProvider>
      </body>
    </html>
  );
}
